from crewai import Agent
from crewai.tools import tool
from agents.answer_agent import call_llm  # tool object
from utils.prompts import IMPROVER_PROMPT_TEMPLATE

# Tool to improve an answer
@tool("improve_answer")
def improve_answer(query: str, docs: str, draft: str) -> str:
    """Uses the AnswerAgent to improve a draft answer based on query and docs."""
    prompt = IMPROVER_PROMPT_TEMPLATE.format(query=query, docs=docs, draft=draft)
    return call_llm.run(prompt)

# Create the Improver Agent
improver_agent = Agent(
    name="ImproverAgent",
    role="answer_improver",
    goal="Improve draft answers using context documents and LM Studio",
    backstory="This agent refines draft answers generated by other agents to make them more accurate and complete.",
    tools=[improve_answer]
)
